### PR TITLE
Various bug fixes

### LINKED ISSUE #17: Sparse matrix transpose and subtraction
The lowering pass currently does not support sparse matrix transpose or subtraction, e.g.

```
export func main()
   A = map f to V;
   B = A';  % fails to compile
   C = A - A;  % fails to compile as well
end
```

### PR DESCRIPTION
**Pull request by stephenchouca**
Fixes #17 (i.e. sparse matrix subtraction) and #52. Also implemented various fixes and workarounds to handle compilation of following cases:

- transpose of sum of two matrices
- sum of transpose of two matrices
- sum of a matrix and its transpose

### CODE REVIEW

**Comment by stephenchouca** [comment]
@fredrikbk Can you review this? Thanks!

File: src/lower/index_expressions/loops.cpp [hunk 1]
```diff
@@ -250,7 +250,8 @@ class CreateSubsetLoopVisitor : public IRVisitor {
   }
 
   void visit(const Sub* op) {
-    not_supported_yet;
+    visitBinaryUnionOperator(op, CompoundOperator::Sub);
+    //not_supported_yet;
```
Comment (gkanwar) [inline src/lower/index_expressions/loops.cpp]: Looks like these comments can be cleaned out

Comment (stephenchouca) [inline src/lower/index_expressions/loops.cpp]: Oops, missed that. Thanks for letting me know!
